# Generated by Django 5.2.3 on 2025-07-02 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('services', '0002_tablebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='details',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Default Service', max_length=100),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
